import game
# import player

print("Welcome to Hangman")
print("   ____")
print("  |    |")
print("  |    o")
print("  |   /|\ ")
print("  |    |")
print("  |   / \ ")
print(" _|_")
print("|   |______")
print("|          |")
print("|__________|")
print("")
print("")
print("")
player1name = raw_input("Type in a very flamboyant name: ")
player2name = raw_input("Type in an even more flamboyant name: ")
print("")
print("")
rounds = input("How many rounds would you like to play? ")
print("Prepare to get hanged " + player1name + " and " + player2name)

gameProcess = game.Game(rounds)
